package com.codealyst.omanprayertimes.ui.theme

import androidx.compose.ui.graphics.Color

val MosqueGreenLight = Color(0xFF246A4B)
val OnMosqueGreenLight = Color(0xFFFFFFFF)
val MosqueGreenContainerLight = Color(0xFFABF2CA)
val OnMosqueGreenContainerLight = Color(0xFF005235)

val SageLight = Color(0xFF4D6356)
val OnSageLight = Color(0xFFFFFFFF)
val SageContainerLight = Color(0xFFD0E8D7)
val OnSageContainerLight = Color(0xFF364B3F)

val MosqueGoldLight = Color(0xFF79590C)
val OnMosqueGoldLight = Color(0xFFFFFFFF)
val MosqueGoldContainerLight = Color(0xFFFFDEA2)
val OnMosqueGoldContainerLight = Color(0xFF5C4200)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF93000A)

val BackgroundLight = Color(0xFFF5FBF4)
val OnBackgroundLight = Color(0xFF171D19)
val SurfaceLight = Color(0xFFF5FBF4)
val SurfaceDimLight = Color(0xFFD6DBD5)
val SurfaceBrightLight = Color(0xFFF5FBF4)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF0F5EF)
val SurfaceContainerLight = Color(0xFFEAEFE9)
val SurfaceContainerHighLight = Color(0xFFE4EAE3)
val SurfaceContainerHighestLight = Color(0xFFDEE4DE)
val OnSurfaceLight = Color(0xFF171D19)
val SurfaceVariantLight = Color(0xFFDCE5DC)
val OnSurfaceVariantLight = Color(0xFF404943)
val OutlineLight = Color(0xFF707972)
val OutlineVariantLight = Color(0xFFC0C9C1)
val ScrimLight = Color(0xFF000000)
val InverseSurfaceLight = Color(0xFF2C322E)
val InverseOnSurfaceLight = Color(0xFFEDF2EC)

val MosqueGreenDark = Color(0xFF8FD5AF)
val OnMosqueGreenDark = Color(0xFF003823)
val MosqueGreenContainerDark = Color(0xFF005235)
val OnMosqueGreenContainerDark = Color(0xFFABF2CA)

val SageDark = Color(0xFFB4CCBC)
val OnSageDark = Color(0xFF203529)
val SageContainerDark = Color(0xFF364B3F)
val OnSageContainerDark = Color(0xFFD0E8D7)

val MosqueGoldDark = Color(0xFFEBC16C)
val OnMosqueGoldDark = Color(0xFF402D00)
val MosqueGoldContainerDark = Color(0xFF5C4200)
val OnMosqueGoldContainerDark = Color(0xFFFFDEA2)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)

val BackgroundDark = Color(0xFF0F1511)
val OnBackgroundDark = Color(0xFFDEE4DE)
val SurfaceDark = Color(0xFF0F1511)
val SurfaceDimDark = Color(0xFF0F1511)
val SurfaceBrightDark = Color(0xFF353B36)
val SurfaceContainerLowestDark = Color(0xFF0A0F0C)
val SurfaceContainerLowDark = Color(0xFF171D19)
val SurfaceContainerDark = Color(0xFF1B211D)
val SurfaceContainerHighDark = Color(0xFF262B27)
val SurfaceContainerHighestDark = Color(0xFF303632)
val OnSurfaceDark = Color(0xFFDEE4DE)
val SurfaceVariantDark = Color(0xFF404943)
val OnSurfaceVariantDark = Color(0xFFC0C9C1)
val OutlineDark = Color(0xFF8A938C)
val OutlineVariantDark = Color(0xFF404943)
val ScrimDark = Color(0xFF000000)
val InverseSurfaceDark = Color(0xFFDEE4DE)
val InverseOnSurfaceDark = Color(0xFF2C322E)

val AdhanLight = Color(0xFFC2410C)
val IqamahLight = MosqueGreenLight

val AdhanDark = Color(0xFFFFB68A)
val IqamahDark = MosqueGreenDark
